# Generated by Django 5.1.7 on 2025-06-02 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_alter_configuracionempresa_asignacion_basica_anual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Descripción del período, e.g. 'Junio 2025'.", max_length=50)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del período')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin del período')),
                ('liquidado', models.BooleanField(default=False, help_text='Indica si ya se ejecutó la liquidación para este período')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Periodo de Nómina',
                'verbose_name_plural': 'Periodos de Nómina',
                'db_table': 'nomina_periodo',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('empresa', 'fecha_inicio', 'fecha_fin')},
            },
        ),
    ]
