# Generated by Django 5.1.7 on 2025-06-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodonomina',
            name='tipo',
            field=models.CharField(choices=[('NOMINA', 'Nómina'), ('PRIMA', 'Prima de Servicios')], default='NOMINA', help_text='Indica si el periodo es de nómina regular o prima.', max_length=10),
        ),
        migrations.AlterField(
            model_name='periodonomina',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periodonomina',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periodonomina',
            name='liquidado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='periodonomina',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
