# Generated by Django 5.1.7 on 2025-06-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_empleado', models.CharField(help_text='Documento de identificación del empleado (p. ej. cédula).', max_length=50, unique=True)),
                ('nombre_empleado', models.CharField(help_text='Nombre completo del empleado.', max_length=255)),
                ('cargo', models.CharField(help_text='Puesto o cargo que ocupa en la empresa.', max_length=100)),
                ('salario_empleado', models.CharField(help_text='Salario del Empleado.', max_length=255)),
                ('fecha_ingreso', models.DateField(help_text='Fecha en que el empleado comenzó a laborar.')),
                ('fecha_retiro', models.DateField(blank=True, help_text='Fecha en que el empleado dejó de laborar (si aplica).', null=True)),
                ('auxilio_transporte', models.BooleanField(default=False, help_text='Indica si el empleado recibe auxilio de transporte.')),
                ('activo', models.BooleanField(default=True, help_text='Si el empleado está activo (True) o ya no (False).')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto del empleado (opcional).', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico del empleado (opcional).', max_length=254)),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó este registro.')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación.')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este empleado.', on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados_empleado',
                'ordering': ['-activo', 'nombre_empleado'],
            },
        ),
    ]
