# Generated by Django 5.1.7 on 2025-06-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='arl',
            field=models.CharField(blank=True, help_text='ARL a la que está afiliado el empleado.', max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Fotografía o avatar del empleado (opcional).', null=True, upload_to='empleados/avatars/'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='eps',
            field=models.CharField(blank=True, help_text='EPS a la que está afiliado el empleado.', max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='grupo_nomina',
            field=models.CharField(blank=True, help_text='Grupo de nómina o área a la que pertenece (opcional).', max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_contrato',
            field=models.CharField(choices=[('TERMINO_FIJO', 'Término fijo'), ('TERMINO_INDEFINIDO', 'Término indefinido'), ('OBRA_O_LABOR', 'Obra o labor'), ('PRACTICANTE', 'Practicante')], default='TERMINO_INDEFINIDO', help_text='Tipo de contrato del empleado.', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='zona_franca',
            field=models.BooleanField(default=False, help_text='Indica si el empleado aplica a zona franca u otro beneficio especial.'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario_empleado',
            field=models.DecimalField(decimal_places=2, help_text='Salario del empleado (en pesos colombianos).', max_digits=12),
        ),
    ]
