# Generated by Django 5.1.7 on 2025-06-01 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_arl_empleado_avatar_empleado_eps_and_more'),
        ('empresas', '0002_configuracionempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_nomina', to='empresas.empresa')),
            ],
        ),
    ]
