# Generated by Django 5.1.7 on 2025-06-02 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptos_nomina', '0001_initial'),
        ('empleados', '0004_remove_empleado_avatar_empleado_descuenta_arl_and_more'),
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, help_text="Cantidad según el tipo de fórmula (horas, días, porcentaje, etc.). Obligatorio si el concepto.tipo_calculo != 'FIJO'.", max_digits=8, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text="Si concepto.tipo_calculo == 'FIJO', aquí se guarda el valor directo.", max_digits=12, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('concepto', models.ForeignKey(help_text='Concepto de nómina asociado (con su tipo_calculo y fórmula).', on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='conceptos_nomina.conceptonomina')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='empleados.empleado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='periodo.periodonomina')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'db_table': 'empleados_novedad',
                'unique_together': {('empleado', 'periodo', 'concepto')},
            },
        ),
    ]
