# Generated by Django 5.1.7 on 2025-06-03 20:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_alter_configuracionempresa_intensidad_horaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='porcentaje_caja',
            field=models.DecimalField(decimal_places=4, default=Decimal('4.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='porcentaje_icbf',
            field=models.DecimalField(decimal_places=4, default=Decimal('3.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='porcentaje_sena',
            field=models.DecimalField(decimal_places=4, default=Decimal('2.00'), max_digits=5),
        ),
    ]
