# Generated by Django 5.1.7 on 2025-06-02 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_alter_configuracionempresa_asignacion_basica_anual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del concepto', max_length=10)),
                ('nombre', models.CharField(help_text='Nombre del concepto', max_length=100)),
                ('tipo', models.CharField(choices=[('DEVENGADO', 'Devengado'), ('DEDUCCION', 'Deducción'), ('PROVISION', 'Provisión'), ('INFORMATIVO', 'Informativo')], help_text='Tipo de concepto', max_length=20)),
                ('forma_calculo', models.CharField(choices=[('FIJO', 'Valor fijo'), ('FORMULA', 'Fórmula'), ('MANUAL', 'Valor manual')], help_text='Forma en la que se calcula', max_length=20)),
                ('formula', models.TextField(blank=True, help_text='Fórmula en caso de que aplique')),
                ('es_base_cotizacion', models.BooleanField(default=False, help_text='¿Hace parte de la base de cotización?')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Concepto de Nómina',
                'verbose_name_plural': 'Conceptos de Nómina',
                'db_table': 'conceptos_nomina',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
    ]
