# Generated by Django 5.1.7 on 2025-06-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptos_nomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptonomina',
            name='codigo',
            field=models.CharField(help_text='Código único del concepto', max_length=30),
        ),
    ]
