# Generated by Django 5.1.7 on 2025-06-02 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conceptos_nomina', '0002_alter_conceptonomina_codigo'),
        ('empleados', '0005_novedad'),
        ('empresas', '0003_alter_configuracionempresa_asignacion_basica_anual_and_more'),
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_liquidacion', models.DateTimeField(auto_now_add=True)),
                ('total_asignaciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_provisiones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='empleados.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='empresas.empresa')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='periodo.periodonomina')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'db_table': 'liquidaciones_liquidacion',
                'ordering': ['-fecha_liquidacion'],
                'unique_together': {('empleado', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='DetalleLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('DEVENGADO', 'Devengado'), ('DEDUCCION', 'Deducción'), ('PROVISION', 'Provisión'), ('INFORMATIVO', 'Informativo')], max_length=20)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conceptos_nomina.conceptonomina')),
                ('novedad', models.ForeignKey(blank=True, help_text='Novedad que originó este detalle (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.novedad')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='liquidaciones.liquidacion')),
            ],
            options={
                'verbose_name': 'Detalle de Liquidación',
                'verbose_name_plural': 'Detalles de Liquidación',
                'db_table': 'liquidaciones_detalle',
                'ordering': ['concepto__codigo'],
            },
        ),
    ]
